{% set name = "xfig" %}
{% set version = "3.2.8a" %}
{% set sha256 = "ba43c0ea85b230d3efa5a951a3239e206d0b033d044c590a56208f875f888578" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: https://sourceforge.net/projects/mcj/files/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make   # [unix]
  host:
    - zlib
    - libpng
    - libjpeg-turbo
    - ghostscript
    - xorg-libx11
    - xorg-libxaw3d
    - xorg-libxpm
    - xorg-libxmu
    - xorg-libxt
  run:
    - libpng
    - libjpeg-turbo
    - ghostscript
    - xorg-libx11
    - xorg-libxaw3d
    - xorg-libxpm
    - xorg-libxmu
    - xorg-libxt

test:
  commands:
    - xfig -v

about:
  home: http://mcj.sourceforge.net
  license: freeware
  summary: 'vector drawing tool'

  description: |
    Xfig is an interactive drawing tool which runs under X Window System
    Version 11 Release 4 (X11R4) or later, on most UNIX-compatible platforms,
    and e.g. under Darwin on the MacIntosh and any X server under Microsoft
    Windows. See the installation section for details. It is freeware, and
    available via anonymous ftp.

extra:
  recipe-maintainers:
    - epruesse
