{% set name = "xfig" %}
{% set version = "3.2.7a" %}
{% set sha256 = "ca89986fc9ddb9f3c5a4f6f70e5423f98e2f33f5528a9d577fb05bbcc07ddf24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: https://sourceforge.net/projects/mcj/files/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - libpng
    - jpeg
    - ghostscript
    - xorg-libx11
    - xorg-libxaw3d
    - xorg-libxpm
    - xorg-libxmu
    - xorg-libxt
  run:
    - libpng
    - jpeg
    - ghostscript
    - xorg-libx11
    - xorg-libxaw3d
    - xorg-libxpm
    - xorg-libxmu
    - xorg-libxt

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
    - xfig -v

about:
  home: http://mcj.sourceforge.net
  license: freeware
  summary: 'vector drawing tool'

  description: |
    Xfig is an interactive drawing tool which runs under X Window System
    Version 11 Release 4 (X11R4) or later, on most UNIX-compatible platforms,
    and e.g. under Darwin on the MacIntosh and any X server under Microsoft
    Windows. See the installation section for details. It is freeware, and
    available via anonymous ftp.

extra:
  recipe-maintainers:
    - epruesse
