travis:
  secure:
    BINSTAR_TOKEN: OsyJ6ZS5kcBp6G8I90tCzDTZpgEprJpSbIlHnv+nwY8Nyf4WNRFmrllQWS1xAWQhRCEBVfCKdmLxL6W5Qhm2jnoFikrfyZrCswLcMNAdvLq+ZtLEkadz5vGi+2JeoXNB1jXRh2Nf2h98S8nC29IRYpUk1i8kQD2zPsvD1HcsVHeKELEL+yRuwBDJ05EfawxCUDKpq+2eiQsoYR62VGTfmmLBlvqzX+QczeTN9ZrZHi60YzgjG/I4cIm6c4CyV8/Aj59SJhqVqAiGQYda6jeZ7Lu4nGk352vQyYHwQ9qOaA6XvjMkTIuVFzfh5FDXKA+ua4t9inAFm5WRs4JKvZxNP1fNGCTp1aAC1ryKdda/12kewiJgl0zqWOS0dRKeZ0v0tz/6pG5N0hhbT3KtZq1Z8A0rhLjxabXxUCOnyaYTGHcTtuGYD+WG4mvLJTW6wvpXceVgLG7A4J+uk7mOlwE7XlbVHb5Xq95LZnmETPlXrz5ljjee9XwBMZ02bi4p63/i7JtAA+HXrmVfHX0LgCwnhZwXCeZ353Sul/9sHTWSrJxvOltkQPjiETWnv3ElXE/TgvjFV06Oi8Jk+5TYEQMD7Y8xkG0Mad1x7RsZcrE/wLDFDiI6+ZxJSKIXd0hUxECUoCwRg/Wy51s378CQdXjDU8fNmPfWKE3aN/mxp6KVeYc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
