travis:
  secure:
    BINSTAR_TOKEN: Hq7VgfHMCkKsnPo2GdTVZJh6vZ6sYGN+XJh6XGnQaYt8BZkO6Z+37KE9F8lpX6SA6rXsUCTj68cmPrUm1YY+SdWsABPxn2h8I2dxDElcchQZ7I6xiGeFFByaZGRf9UNmzqJyOmx1CY8y89xxRAR37Q1q6Jx2R9KQ5RbLFdN8FGmqL3oyEhnitWB6nocAGhWnDEVWv3kaIG2EB1aaAMxa7zoJwlSEsDAum1NCfk5LhMXfn15eNjQpTEacGuFNbL7qb3skVVWOH4pHhzSiLEpMxAaipRRHGGy242XqYbSWOUY0J+CiRSgTwP5753QWoUnI+5BW4Ufv04+U6DdJDf4J73WA8o/hpRBs1EcXU21HDqdOzL6nC8C+z4mUNftf78KrHrW22f8wanEb0nNq0ipBINQ3ccYGxKAtJcpY6aqrkx8EaNUGb3VhpAFJQ0qNUdQZAGPGRZA7VoLcWyF5TG1Se+VzXyEKnfN8ievmHppYfH49zy+BmrsjXFA8mGfg0yT4INOnpt9XXm01O40EgJTjOhln3/vTrgahGfheqYgR9Lj8MnRfTJYb7adjx82GWEwae3dkCu1JcjyQS68Cq/wsVwk3e3zXZmNoDmOh9DIYxBorISQk5ow1lQHKCoY7oXDTHXuAmOE54KbRIrjLravpY3pXpao0++SpWEfaXmp0fKk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
